name: Update IMDb Recommendations

on:
  schedule:
    - cron: "0 6 * * *" # Runs every day at 6:00 UTC
  workflow_dispatch:

jobs:
  update-recommendations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run IMDb scraper
        run: python .github/scripts/imdb_recommender.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add recommendations.html
          git commit -m "🤖 Auto-update IMDb recommendations"
          git push
