name: Update Latest Page

on:
  workflow_dispatch:

jobs:
  update-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run script to update latest.html
        run: python .github/scripts/update_latest.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add latest.html
          git commit -m "🆕 Manually updated Latest section" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/berickizer/movie-website.git HEAD:main
